### ISSUE TITLE
Tasks...

### ISSUE THREAD

**Issue by eribertomota** [resurrecting-open-source-projects/outguess#2]
- [x] Remove all warnings
- [x] Move all source code to src/
- [x] Rename configure.in to configure.ac and modernize it
- [x] Rename Makefile.in to Makefile.am and modernize it
- [x] Update README
- [ ] Remove embedded jpeg-6b-steg and make the source code depend of a shared lib

**Comment by hoijui** [comment]
regarding *jpeg-6b-steg* ... I was looking for that library online, but I could not find it anywhere else then in outguess. I am too lazy to put it into an other repo and make a shared lib and link to it and make sure it gets installed and.. it just makes live harder for people using/compiling outguess in the end, as nobody else uses that lbrary.

I never used autotools as a dev, only as a user, and I do not want to learn it, so someone else would have to do those things.
I would rather convert everything to CMake, then doing that.

**Comment by eribertomota** [comment]
The lib is here: http://www.ijg.org/files/

The newest version is jpegsrc.v9d, 2020-01-12

**Comment by eribertomota** [comment]
autotools is more or less easy for me... I can try if you want it. I prefer autotools but you can convert to CMake too.

**Comment by eribertomota** [comment]
Now I was looking for libjpeg in Debian and libjpeg9[1], used by outguess, is blocked[2] forever. Debian and other distros are using libjpeg-turbo[3][4][5].

[1] https://tracker.debian.org/pkg/libjpeg9
[2] https://release.debian.org/britney/hints/elbrus
[3] https://tracker.debian.org/pkg/libjpeg-turbo
[4] https://libjpeg-turbo.org/
[5] https://repology.org/project/libjpeg-turbo/versions

So, is not a good idea use libjpeg9.

**Comment by eribertomota** [comment]
After review all outguess structure and prepare a new install system from zero, I am convinced that is not a good idea to remove embedded and modified JPEG. Consequently, considering all other tasks done, I am closing this issue. Thanks a lot for your help.
