### ISSUE TITLE
Unknown data type (for .pnm files)

### ISSUE THREAD

**Issue by eribertomota** [resurrecting-open-source-projects/outguess#6]
When trying to use OutGuess with .pnm files, the same error is shown:

$ ./src/outguess -k "secret-key-001" -d tests/message.txt tests/test.pnm test-with-message.pnm
Embedding a message...
Unknown data type of test.pnm

**Comment by daltomi** [comment]
Hi @eribertomota 
I still have not decided whether to fork this project, in the meantime I am sending you a patch file that solves this problem.
The "problem" is here:
https://github.com/resurrecting-open-source-projects/outguess/blob/3f6af3b3d72c88293c0a651a8672a81b429efa04/src/pnm.c#L53

It is correct, according to [Wikipedia](https://en.wikipedia.org/wiki/Netpbm#File_formats), that a PPM file has a **.pnm** extension too. 

[pnm - Netpbm superformat](http://netpbm.sourceforge.net/doc/pnm.html) _The PNM format is just an abstraction of the PBM, PGM, and PPM formats. I.e. the name "PNM" refers collectively to PBM, PGM, and PPM_

Internally `pnm.c` supports PPM and PGM, so with more reason I think that the extension `.pnm` should be supported.

So all I did is add another field to the `struct` to allow another extension name to be detected.
[support_alternative_extension.patch.zip](https://github.com/resurrecting-open-source-projects/outguess/files/7062947/support_alternative_extension.patch.zip)

Cheers!

**Comment by eribertomota** [comment]
Thanks a lot @daltomi. It worked fine.
